export const homeObjOne = {
  id: 'howitworks',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'How it works',
  headline: 'Safe, secure, and encrypted',
  description: 'Serverless cloud-native architecture built with Firebase development platform and encrypted using Google Cloud Key Management Service',
  buttonLabel: 'Demo',
  imgStart: true,
  img: require('../../images/svg-1.svg').default,
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: 'pricing',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Pricing',
  headline: 'Affordable and scalable',
  description: 'We provide the app free of charge to all people experiencing homelessness and the complimentary software features at an affordable subscription fee for organzations',
  buttonLabel: 'Learn more',
  imgStart: false,
  img: require('../../images/svg-2.svg').default,
  alt: 'Phone',
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: 'download',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Download the app',
  headline: 'Getting started is extremely easy',
  description: 'Get access to our app and the features that make tackling homelessness manageable',
  buttonLabel: 'Get started',
  imgStart: true,
  img: require('../../images/svg-3.svg').default,
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
};